### ISSUE TITLE
Add icons that hold the current color values for Primary, Secondary, and Tertiary into the Color Picker Popup.

### ISSUE THREAD

**Issue by Axium7** [versile2/ThemeCreatorMudBlazor#1]
Can you please add three icons (Primary, Secondary, and Tertiary) to the Color Picker Popup.

Each will hold the value of the current Primary, Secondary and Tertiary colors, respectively.   When I click on each individual icon, the current color value for that icon (Primary, Secondary, and Tertiary), will be set to the color picker Popup.

Thank you.

**Comment by versile2** [comment]
This is possible. I would have to remove the button that I'm using to "display" it to a user. Then use the palette icon centered where the button is x 3. With each being one of the Primary/Secondary/Tertiary colors. I'll add a tooltip to explain what it's doing when you click one. I also believe making the popover a dialog might work better as well. I'll queue those up.

**Comment by versile2** [comment]
Changed from Popover to MudExDialog allowing for animation and draggable features. 
Added 3 "copy from" options for primary, secondary, tertiary colors. 
Removed _hasBeenOpened variable, prerendering is not an issue any more. 
Added StyleService to get current primary/secondary/tertiary colors to ensure the copy from buttons keep initial values.  
Removed old style button. It still exists in the ColorPicker itself as the bar on bottom left. It was redundant and made the UI feel cluttered.
Fixed bug in Snackbarchip.

**Comment by Axium7** [comment]
Incredible work.  Thank you Versile.

**Comment by Axium7** [comment]
Can you default the color picker to the second option with the clear color gradients.

**Comment by Axium7** [comment]
The Secondary and Tertiary saved Colors in the Color Picker are not working.

**Comment by versile2** [comment]
> Can you default the color picker to the second option with the clear color gradients.

after other opinions most people prefer the first option so leaving it as is for now.
