### ISSUE TITLE
Changes to theme values not visible 

### ISSUE THREAD

**Issue by N0M3X** [versile2/ThemeCreatorMudBlazor#17]
Hello Versile2,

I have recently started working with your ThemeCreator. First of all, big praise for this great tool. 

I use the “Dark Mode” with the “Palette Dark” to create a theme. 

Unfortunately, I could not find any changes for the following theme values. Would you be so kind as to let me know what the individual theme values change/affect?

- BackgroundGrey
- ChipDefault
- ChipDefaultHover
- DarkLighten
- DividerLight
- ErrorLighten
- GrayDark
- GrayDefault
- GrayLighter
- HoverOpacity
- InfoLighten
- OverlayLight
- PrimaryLighten
- SecondaryLighten
- SuccessLighten
- TableStriped
- WarningLighten

Thanks & regards
Joerg

**Comment by versile2** [comment]
Unfortunately I have not documented each theme item in Mudblazor. I would suggest getting the cssvariable for that value opening the MudBlazor solution and searching for it. That would tell you what that theme value affects. If you wanted to be a huge help you could create a table, name, css variable, affects that I could integrate into the application.

Versile

**Comment by N0M3X** [comment]
Can you tell me where exactly I can search for the css variables in the Mudblazer solution?

**Comment by versile2** [comment]
This page lists all the values and css variables
https://mudblazor.com/customization/default-theme#mudtheme

Take the css variable values, for example we are going to look up BackgroundGray so we grabbed --mud-palette-background-gray. Go to the mudblazor github. Click search, paste --mud-palette-background-gray into search click on mudblazor and note where it's listed. In this case we've got 20 files as a result. We need to notate what each file is, if it should be listed as affecting or if it's part of something else unrelated. I've got to look up each file and see what it is. Also the first result is them using it to assign to class, I might search that class. When I'm done I'll have a list of spot's it's used in. so my first entry would be

BackgroundGray, --mud-palette-background-gray, used as background color for.... and ... and ...

When I have a full list I'll add tooltip notations so you could hover over an item and know what it changes.

![Screenshot 2024-11-06 090633](https://github.com/user-attachments/assets/4d4cca57-af2f-4376-aa60-8199cce95e42)
![Screenshot 2024-11-06 090708](https://github.com/user-attachments/assets/4e0ad050-4eb7-4f37-a68c-bb1ac7f41346)

**Comment by versile2** [comment]
let me know if you get a table I'll put it in as tooltips
