### ISSUE TITLE
X (Cancel) in the Right most Position in the Color Picker

### ISSUE THREAD

**Issue by Axium7** [versile2/ThemeCreatorMudBlazor#5]
In the color Picker put the X (Cancel) in the Right most position.   Users are accustomed to seeing the X in the right most  position.

**Comment by versile2** [comment]
guess I wanted it there to prevent more accidental reverts. Makes sense though. maybe I'll add just a touch of spacing between the other buttons and cancel button. And not like an accidental revert is that hard to get over.
